In [3]:
import numpy as np
# file = np.load('data/q3/q3.npy')

In [31]:
file = np.fromfile('/home/akshay/Downloads/1607016961.bin', dtype=np.float64)

In [32]:
file.shape

(343,)

In [21]:
file.shape, file.reshape(-1, 3).shape

((171,), (57, 3))

In [1]:
import open3d as o3d

Jupyter environment detected. Enabling Open3D WebVisualizer.
[Open3D INFO] WebRTC GUI backend enabled.
[Open3D INFO] WebRTCWindowSystem: HTTP handshake server disabled.


In [2]:
pcd = o3d.io.read_point_cloud("/home/akshay/Downloads/1607016961.pcd")

[Open3D WARNING] [CheckHeader] PCD has no data.
[Open3D WARNING] Read PCD failed: unable to parse header.


In [4]:
import numpy as np
file = np.loadtxt("/home/akshay/Downloads/picking_list.txt")


ValueError: could not convert string to float: '-11.548953056335,-0.191504895687,3.094958066940'

In [2]:
import numpy as np
points = np.zeros((0, 3))
with open('./picking_list_3.txt', 'r') as f:
    lines = f.readlines()
    for line in lines:
        line = line.split(',')
        point = np.asarray([float(line[0]), float(line[1]), float(line[2])])
        points = np.concatenate((points, point.reshape(-1, 3)), axis=0)


In [3]:
import open3d as o3d
pcd = o3d.geometry.PointCloud()
pcd.points = o3d.utility.Vector3dVector(points)
o3d.visualization.draw_geometries([pcd])

Jupyter environment detected. Enabling Open3D WebVisualizer.
[Open3D INFO] WebRTC GUI backend enabled.
[Open3D INFO] WebRTCWindowSystem: HTTP handshake server disabled.


In [4]:
import numpy as np
np.save("sample3", points)
sample = np.load('./sample3.npy')

In [5]:
sample.shape

(11, 3)

In [4]:
import open3d as o3d
import numpy as np

In [5]:
pcd = o3d.io.read_point_cloud('/home/akshay/Downloads/pcd/1607016959.467473000.pcd')

In [6]:
points = np.asarray(pcd.points)

In [7]:
points.shape

(23423, 3)

In [ ]:
o3d.visualization.draw_geometries([pcd])

In [3]:
import open3d as o3d
import numpy as np
pcd = o3d.io.read_point_cloud('/home/akshay/Downloads/Mesh.pcd')
o3d.visualization.draw_geometries([pcd])

In [6]:
points = np.asarray(pcd.points)

In [7]:
points.shape

(2997, 3)

In [8]:
points[:, 0].min(), points[:, 0].max(), points[:, 1].min(), points[:, 1].max(), points[:, 2].min(), points[:, 2].max()

(16.588783264160156,
 315.4676513671875,
 0.00010000000474974513,
 1500.0001220703125,
 12.097312927246094,
 309.63775634765625)

In [9]:
points[:, [1, 2]] = points[:, [2, 1]]

In [10]:
points[:, 0].min(), points[:, 0].max(), points[:, 1].min(), points[:, 1].max(), points[:, 2].min(), points[:, 2].max()


(16.588783264160156,
 315.4676513671875,
 12.097312927246094,
 309.63775634765625,
 0.00010000000474974513,
 1500.0001220703125)

In [13]:
points = points[points[:, 2] > 1]
points = points[points[:, 2] < 1450]
points.shape

(2611, 3)

In [14]:
pcd = o3d.geometry.PointCloud()
pcd.points = o3d.utility.Vector3dVector(points)
o3d.visualization.draw_geometries([pcd])

In [15]:
np.save('./tree.npy', points)

In [1]:
import numpy as np

In [2]:
P = np.asarray([[1, 0, 0, 0],
                [0, 1, 0, 0],
                [0, 0, 0, 1]])
P_plus = P.T@np.linalg.inv((P@P.T))

In [3]:
P_plus

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 0.],
       [0., 0., 1.]])

In [4]:
a = np.asarray([[0, 1, 1],
                [-1, 0, 1],
                [-1, -1, 0]])

In [5]:
P.T@a@P

array([[ 0,  1,  0,  1],
       [-1,  0,  0,  1],
       [ 0,  0,  0,  0],
       [-1, -1,  0,  0]])

In [31]:
from scipy.spatial.transform import Rotation
import numpy as np

In [32]:
angles = np.asarray([45, 45, 45])

In [33]:
from math import degrees


r = Rotation.from_euler("zyx", angles, degrees=True)
rotation_matrix = r.as_matrix()

In [34]:
print(rotation_matrix)

[[ 0.5        -0.5         0.70710678]
 [ 0.85355339  0.14644661 -0.5       ]
 [ 0.14644661  0.85355339  0.5       ]]


In [35]:
def create_F(P, P_, C, C_):
    C = np.concatenate((C, np.ones((1, ))), axis=0)
    print(C.shape)
    e_ = P_@C
    e_cross = np.asarray([[0, -e_[2], e_[1]],
                          [e_[2], 0, -e_[0]],
                          [-e_[1], e_[0], 0]])
    P_plus = P.T@np.linalg.inv(P@P.T)
    return e_cross@P_@P_plus

In [36]:
def construct_P(K, angles, C):
    r = Rotation.from_euler("zyx", angles, degrees=True)
    rotation_matrix = r.as_matrix()
    identity_C = np.concatenate((np.identity(3), C.reshape(3, 1)), axis=1)
    P = K@rotation_matrix@identity_C
    return P

In [37]:
# K = np.identity(3)
angles1 = np.asarray([0, 0, 0])
angles2 = np.asarray([45, 45, 45])
C1 = np.asarray([0, 0, 0])
C2 = np.asarray([5, 5, 5])
# P1 = construct_P(K, angles1, C1)
# P2 = construct_P(K, angles2, C2)

In [38]:
K_2 = np.asarray([[1/2, 0, 0],
                [0, 1/2, 0],
                [0, 0, 1]])
K_1 = np.identity(3)

In [42]:
P1 = construct_P(K_1, angles1, C1)
P2 = construct_P(K_1, angles2, C2)
F = create_F(P1, P2, C1, C2)
F / F[-1, -1]
np.linalg.matrix_rank(F)

(4,)


2

In [41]:
P1 = construct_P(K_2, angles1, C1)
P2 = construct_P(K_2, angles2, C2)
F = create_F(P1, P2, C1, C2)
F / F[-1, -1]
np.linalg.matrix_rank(F)

(4,)


2

In [1]:
P1_n = construct_P(K, angles1, C1/2)
P2_n = construct_P(K, angles2, C2/2)

NameError: name 'construct_P' is not defined

In [2]:
import numpy as np

In [3]:
P_ = np.asarray([[0, -1, 0, 0],
                 [1, 0, 0, 0],
                 [0, 0, 0, 1]])
H = np.asarray([[1/2, 0, 0, 0],
                [0, 1/2, 0, 0],
                [0, 0, 1/2, 0],
                [1, 1, 1, 2]])

In [5]:
P_@H

array([[ 0. , -0.5,  0. ,  0. ],
       [ 0.5,  0. ,  0. ,  0. ],
       [ 1. ,  1. ,  1. ,  2. ]])

In [6]:
from scipy.linalg import null_space

In [14]:
a = np.asarray([[2, 0, 0],
                [0, 3, 1],
                [4, 6, 2]])

In [19]:
x = null_space(a.T)

In [20]:
x.reshape(-1) / x.reshape(-1)[1]

array([ 1. ,  1. , -0.5])

In [43]:
A = np.asarray([[0, -1, -1],
                [1, 0, -1],
                [1, 1, 0]])

In [44]:
A

array([[ 0, -1, -1],
       [ 1,  0, -1],
       [ 1,  1,  0]])

In [45]:
np.linalg.matrix_rank(A)

2

In [1]:
import numpy as np

In [2]:
tree = np.load('./tree.npy')

In [3]:
np.savetxt('tree.csv', tree)

In [4]:
tree = np.genfromtxt('tree.csv')

In [5]:
tree.shape

(2611, 3)

In [2]:
import numpy as np
tree = np.load('./sample.npy')
np.savetxt('sample.csv', tree)

In [1]:
import numpy as np

In [2]:
x = np.random.randint(0, 10, (5, 5))

In [3]:
x

array([[6, 9, 8, 9, 9],
       [4, 3, 6, 4, 2],
       [4, 5, 3, 8, 8],
       [8, 5, 6, 1, 5],
       [2, 3, 4, 9, 0]])

In [7]:
rows, col = np.meshgrid(np.arange(3), np.arange(3))

In [9]:
rows, col = rows.reshape(-1), col.reshape(-1)

In [22]:
col, rows,
col_n =  np.int16(col+3)

In [26]:
slices = x[col[:, np.newaxis] 3]

TypeError: only integer scalar arrays can be converted to a scalar index

In [34]:
y = np.lib.stride_tricks.sliding_window_view(x, (3, 3))[::2, ::2]

In [35]:
# k_size = 3*3
x, y

(array([[6, 9, 8, 9, 9],
        [4, 3, 6, 4, 2],
        [4, 5, 3, 8, 8],
        [8, 5, 6, 1, 5],
        [2, 3, 4, 9, 0]]),
 array([[[[6, 9, 8],
          [4, 3, 6],
          [4, 5, 3]],
 
         [[8, 9, 9],
          [6, 4, 2],
          [3, 8, 8]]],
 
 
        [[[4, 5, 3],
          [8, 5, 6],
          [2, 3, 4]],
 
         [[3, 8, 8],
          [6, 1, 5],
          [4, 9, 0]]]]))

In [1]:
import open3d as o3d
import numpy as np

Jupyter environment detected. Enabling Open3D WebVisualizer.
[Open3D INFO] WebRTC GUI backend enabled.
[Open3D INFO] WebRTCWindowSystem: HTTP handshake server disabled.


In [2]:
pcd = o3d.io.read_point_cloud("./forest.pcd")
o3d.visualization.draw_geometries([pcd])

In [3]:
def plot_req_points(points):
    pcd = o3d.geometry.PointCloud()
    pcd.points = o3d.utility.Vector3dVector(points)
    o3d.visualization.draw_geometries([pcd])

In [4]:
def crop(points, 
         x_min, 
         x_max, 
         y_min, 
         y_max, 
         z_min, 
         z_max):
    req_idx = (points[:, 0] >= x_min) & \
              (points[:, 0] <= x_max) & \
              (points[:, 1] >= y_min) & \
              (points[:, 1] <= y_max) & \
              (points[:, 2] >= z_min) & \
              (points[:, 2] <= z_max)
    return points[req_idx]

In [5]:
points = np.asarray([pcd.points])[0]
points[:, [1, 2]] = points[:, [2, 1]]
points.shape
min_z, max_z = points[:, -1].min(), points[:, -1].max()
min_x, max_x = points[:, 0].min(), points[:, 0].max()
min_y, max_y = points[:, 1].min(), points[:, 1].max()
min_x, max_x, min_y, max_y, min_z, max_z

(0.1360059380531311,
 13282.5859375,
 8.460957906208932e-05,
 9300.0,
 0.0,
 2021.1820068359375)

In [6]:
req_points = crop(points, 0, 35000, 0, 35000, 0, 2021)

In [7]:
plot_req_points(req_points)

In [7]:
## for normal points
normal_xs = np.linspace(0, max_x, 10)
normal_ys = np.linspace(0, max_y, 13)
xs, ys = np.meshgrid(normal_xs, normal_ys)

In [8]:
xs = xs.flatten()
ys = ys.flatten()

In [9]:
radius = 500
points_new = np.zeros((0, 3))

In [10]:
for patch_no, (x, y) in enumerate(zip(xs, ys)):
    # print(x, y)
    req_points = crop(points, x, x+2*radius, y, y+2*radius, 0, max_z)
    # plot_req_points(req_points)
    if req_points.shape[0] >= 100:
        np.savetxt(f'./forest/{patch_no}.csv', req_points)
        points_new = np.concatenate((points_new, req_points), axis=0)
    # print(req_points.shape)
print(points_new.shape)

(778071, 3)


In [11]:
pcd = o3d.geometry.PointCloud()
pcd.points = o3d.utility.Vector3dVector(points_new)
o3d.io.write_point_cloud('./forest_new.pcd', pcd)

True